version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis-master:
    image: redis:latest
    container_name: redis_master
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data
    networks:
      - redis-net

  redis-replica:
    image: redis:latest
    container_name: redis_replica
    ports:
      - "6380:6379"
    command: [ "redis-server", "--slaveof", "redis-master", "6379", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data
    networks:
      - redis-net

  redis-replica2:
    image: redis:latest
    container_name: redis_replica2
    ports:
      - "6381:6379"
    command: [ "redis-server", "--slaveof", "redis-master", "6379", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data
    networks:
      - redis-net

volumes:
  redis_data:

networks:
  redis-net:
    driver: bridge
